name: Server CI Pipeline

on:
  pull_request:

env:
  COMPOSE_FILE: ./compose.ci.yml
  SERVER_IMAGE: ghcr.io/${{ github.repository }}/server/${{ github.ref_name }}:latest
  ADMIN_IMAGE: ghcr.io/${{ github.repository }}/admin/${{ github.ref_name }}:latest

  APP_KEY: NOT_AN_REAL_APP_KEY
  ARCWELL_INSTANCE_ID: arcweb-ci
  ARCWELL_INSTANCE_NAME: CI Arcwell Server"
  ARCWELL_REGISTER_ENABLED: true
  ARCWELL_KEY: "LOCAL-DEV-SERVER"
  ARCWELL_NODE: "Arcweb/Dev-Node"
  DB_DATABASE: arcwell_test
  DB_HOST: db
  DB_PASSWORD: arcwell
  DB_PORT: 5432
  DB_USER: arcwell
  HOST: 0.0.0.0
  LOG_LEVEL: info
  NODE_ENV: development
  PORT: 3333
  SMTP_FROM_ADDRESS: arcwell@example.com
  SMTP_FROM_NAME: "Arcwell Admin"
  SMTP_HOST: mailpit
  SMTP_PASSWORD: arcwell
  SMTP_PORT: 1025
  SMTP_USER: arcwell
  TZ: UTC

jobs:
  changes:
    runs-on: ubuntu-latest

    outputs:
      server: ${{ steps.filter.outputs.server }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Filter paths
        uses: dorny/paths-filter@v3
        id: filter
        with:
          list-files: csv
          filters: |
            server:
              - 'packages/server/**'

  build-server-and-test:
    needs: changes
    if: ${{ needs.changes.outputs.server == 'true' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Server Image
        uses: docker/build-push-action@v5
        with:
          context: ./packages/server
          file: ./packages/server/Dockerfile
          target: develop
          build-args: |
            NODE_ENV=development
            PORT=3333
          push: true
          tags: ${{ env.SERVER_IMAGE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Confirm containers are up
        run: |
          docker compose up -d db server
          set -e
          echo "Checking health of the server..."
          # Retry the health check up to 10 times with a 10-second interval
          for i in {1..5}; do
            if docker compose exec server curl --fail http://localhost:3333/health; then
              echo "Health check passed!"
              break
            else
              echo "Health check failed, retrying in 5 seconds..."
              sleep 5
            fi
          done
          
          # If we exhausted all retries and curl still fails, exit the job
          if ! docker compose exec server curl --fail http://localhost:3333/health; then
            echo "Health check failed after 10 attempts. Exiting."
            docker compose logs server
            exit 1
          fi

      - name: Lint Server
        run: |
          docker compose exec server npm run lint

      - name: Test Server
        run: |
          docker compose exec server npm run test
